language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - TESTBENCH_VERSION=2.1.*
  - TESTBENCH_VERSION=2.2.*
  - TESTBENCH_VERSION=2.3.*

before_script:
  - composer self-update
  - composer require orchestra/testbench:${TESTBENCH_VERSION} satooshi/php-coveralls:dev-master --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  exclude:
    - php: 5.3
      env: TESTBENCH_VERSION=2.2.*
    - php: 5.3
      env: TESTBENCH_VERSION=2.3.*
